# Generated by Django 5.0.6 on 2024-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="sentiment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POSITIVE", "POSITIVE"),
                    ("NEUTRAL", "NEUTRAL"),
                    ("NEGATIVE", "NEGATIVE"),
                ],
                max_length=10,
            ),
        ),
    ]
