# Generated by Django 5.0.6 on 2024-06-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0006_alter_playlist_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playlist", options={"ordering": ["-is_favorite", "-created_at"]},
        ),
    ]
