# Generated by Django 5.0.6 on 2024-06-10 02:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_moviereview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(old_name="MovieReview", new_name="Review",),
    ]
