# Generated by Django 5.0.6 on 2024-06-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0008_rename_moviereview_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
    ]
