# Generated by Django 5.0.6 on 2024-06-10 03:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0009_movie_review_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="review", unique_together={("user", "movie")},
        ),
    ]
