# Generated by Django 5.0.6 on 2024-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfollowing", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(name="userfollowing", unique_together=set(),),
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.UniqueConstraint(
                fields=("user_id", "following_user_id"), name="unique_followers"
            ),
        ),
    ]
