# Generated by Django 5.0.6 on 2024-06-07 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=150)),
                ("movie_tmdb_id", models.IntegerField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LIKED_MOVIE", "LIKED_MOVIE"),
                            ("REVIEWED_MOVIE", "REVIEWED_MOVIE"),
                            ("FOLLOWED_USER", "FOLLOWED_USER"),
                            ("ADDED_MOVIE_TO_PLAYLIST", "ADDED_MOVIE_TO_PLAYLIST"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "followed_username",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_user",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
    ]
