# Generated by Django 5.0.6 on 2024-06-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_useractivity"),
    ]

    operations = [
        migrations.RemoveField(model_name="useractivity", name="description",),
        migrations.AddField(
            model_name="useractivity",
            name="activity",
            field=models.CharField(
                choices=[
                    ("LIKED_MOVIE", "LIKED_MOVIE"),
                    ("REVIEWED_MOVIE", "REVIEWED_MOVIE"),
                    ("FOLLOWED_USER", "FOLLOWED_USER"),
                    ("ADDED_MOVIE_TO_PLAYLIST", "ADDED_MOVIE_TO_PLAYLIST"),
                ],
                default="LIKED_MOVIE",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useractivity",
            name="object",
            field=models.CharField(default="LIKED_MOVIE", max_length=20),
            preserve_default=False,
        ),
    ]
