# Generated by Django 5.0.6 on 2024-05-29 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_userfollowing_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userfollowing", name="unique_followers",
        ),
        migrations.RenameField(
            model_name="userfollowing",
            old_name="following_user_id",
            new_name="following_user",
        ),
        migrations.RenameField(
            model_name="userfollowing", old_name="user_id", new_name="user",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="userfollowing",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userfollowing", unique_together={("user", "following_user")},
        ),
    ]
