# Generated by Django 5.0.6 on 2024-06-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="review_id",
            field=models.UUIDField(null=True),
        ),
    ]
