# Generated by Django 5.0.6 on 2024-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_useractivity_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useractivity", old_name="activity", new_name="type",
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="object",
            field=models.CharField(max_length=100),
        ),
    ]
