# Generated by Django 5.0.6 on 2024-06-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_customuser_profile_picture"),
        ("user", "0004_useractivity_review_id"),
    ]

    operations = []
