# Generated by Django 5.0.6 on 2024-06-05 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_useractivity_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="useractivity", name="object",),
        migrations.RemoveField(model_name="useractivity", name="user",),
        migrations.AddField(
            model_name="useractivity",
            name="description",
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useractivity",
            name="followed_username",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_user",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="movie_tmdb_id",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useractivity",
            name="username",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
