# Generated by Django 5.0.6 on 2024-06-16 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_merge_20240614_1756"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
