# Generated by Django 5.0.6 on 2024-06-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_useractivity_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
